name: Linux

on: [push, pull_request]

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
          - runner: ubuntu-22.04-arm
            name: aarch64

    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        cache: false
        components: rustfmt
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y clang cmake libssl-dev


    - name: Determine architecture-specific paths
      id: paths
      run: |
        ARCH=$(uname -m)
        if [ "$ARCH" = "x86_64" ]; then
          echo "libdir=/usr/lib/x86_64-linux-gnu" >> $GITHUB_OUTPUT
        elif [ "$ARCH" = "aarch64" ]; then
          echo "libdir=/usr/lib/aarch64-linux-gnu" >> $GITHUB_OUTPUT
        fi

    - name: Build
      env:
        OPENSSL_NO_VENDOR: "1"
        OPENSSL_ROOT_DIR: /usr
        OPENSSL_INCLUDE: /usr/include
        OPENSSL_LIB_DIR: ${{ steps.paths.outputs.libdir }}
      run: |
       cargo build --release
       pushd moonlight-web/web-server
       npm install
       npm run build
       mv dist static
       popd

       mv target/release/streamer streamer
       mv target/release/web-server web-server
       mv moonlight-web/web-server/static static


    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: moonlight-web-${{ matrix.arch.name }}-unknown-linux-gnu
        path: |
          streamer
          web-server
          static
