name: Linux

on: [push, pull_request]

jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        arch:
          - runner: ubuntu-22.04
            name: x86_64
            target: x86_64-unknown-linux-musl
          - runner: ubuntu-22.04-arm
            name: aarch64
            target: aarch64-unknown-linux-musl

    name: ${{ matrix.arch.name }}
    runs-on: ${{ matrix.arch.runner }}

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: nightly
        target: ${{ matrix.arch.target }}
    - uses: actions/setup-node@v6
      with:
        node-version: 24
    - name: Install musl and build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y musl-tools musl-dev clang cmake


    - name: Build
      env:
        CC: musl-gcc
        OPENSSL_STATIC: "1"
      run: |
       cargo build --release --target ${{ matrix.arch.target }}
       pushd moonlight-web/web-server
       npm install
       npm run build
       mv dist static
       popd


    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: moonlight-web-${{ matrix.arch.name }}-unknown-linux-musl
        path: |
          target/${{ matrix.arch.target }}/release/streamer
          target/${{ matrix.arch.target }}/release/web-server
          moonlight-web/web-server/static
